#!/bin/sh -x
ocpasswd -c /etc/ocserv/ocpasswd -d fjxk4t
ocpasswd -c /etc/ocserv/ocpasswd -d vak3n6
ocpasswd -c /etc/ocserv/ocpasswd -d swc8y9
ocpasswd -c /etc/ocserv/ocpasswd -d fjxk4t
ocpasswd -c /etc/ocserv/ocpasswd -d s5rp6g
ocpasswd -c /etc/ocserv/ocpasswd -d y2qg5m
ocpasswd -c /etc/ocserv/ocpasswd -d Ef3MsKh
ocpasswd -c /etc/ocserv/ocpasswd -d C8xNQNn3
ocpasswd -c /etc/ocserv/ocpasswd -d 7csk4LDn
ocpasswd -c /etc/ocserv/ocpasswd -d Ns3kdHcz
ocpasswd -c /etc/ocserv/ocpasswd -d FtBRN27E
ocpasswd -c /etc/ocserv/ocpasswd -d CxugfN6L
ocpasswd -c /etc/ocserv/ocpasswd -d KSYfuq5K
ocpasswd -c /etc/ocserv/ocpasswd -d G2bdrUKK
ocpasswd -c /etc/ocserv/ocpasswd -d bNcAA58g
ocpasswd -c /etc/ocserv/ocpasswd -d 85j5GGLS
ocpasswd -c /etc/ocserv/ocpasswd -d vGzEs7tC
ocpasswd -c /etc/ocserv/ocpasswd -d JHXQ2zxH
ocpasswd -c /etc/ocserv/ocpasswd -d 7nVysDu
ocpasswd -c /etc/ocserv/ocpasswd -d 5pvxQQrT
ocpasswd -c /etc/ocserv/ocpasswd -d G3repvyp
ocpasswd -c /etc/ocserv/ocpasswd -d VyTW3L5
ocpasswd -c /etc/ocserv/ocpasswd -d Fpf8tBu
ocpasswd -c /etc/ocserv/ocpasswd -d PMvAb4g
ocpasswd -c /etc/ocserv/ocpasswd -d wkGXY2v
ocpasswd -c /etc/ocserv/ocpasswd -d sq3NrfZ
ocpasswd -c /etc/ocserv/ocpasswd -d mS7vaEH
ocpasswd -c /etc/ocserv/ocpasswd -d Lkvf7MU
ocpasswd -c /etc/ocserv/ocpasswd -d x2nfMkU
ocpasswd -c /etc/ocserv/ocpasswd -d Ze6MDPwB
ocpasswd -c /etc/ocserv/ocpasswd -d 9sCxpcxf
ocpasswd -c /etc/ocserv/ocpasswd -d PFzqN9Ph
ocpasswd -c /etc/ocserv/ocpasswd -d CbF3dZDW
ocpasswd -c /etc/ocserv/ocpasswd -d NafqyNf6
ocpasswd -c /etc/ocserv/ocpasswd -d nurphq5v
ocpasswd -c /etc/ocserv/ocpasswd -d 6Wq3EZq6
ocpasswd -c /etc/ocserv/ocpasswd -d JpXa6Why
ocpasswd -c /etc/ocserv/ocpasswd -d 4mr8Xshd
ocpasswd -c /etc/ocserv/ocpasswd -d dMeHSV47
ocpasswd -c /etc/ocserv/ocpasswd -d maWALD8k
ocpasswd -c /etc/ocserv/ocpasswd -d ghu2wmeU
ocpasswd -c /etc/ocserv/ocpasswd -d gTWd9uxC
ocpasswd -c /etc/ocserv/ocpasswd -d sDLZEPM5
ocpasswd -c /etc/ocserv/ocpasswd -d j7fLqRSK
ocpasswd -c /etc/ocserv/ocpasswd -d dXh2qbc9
