#!/bin/sh -x
ocpasswd -c /etc/ocserv/ocpasswd -d byeg94
ocpasswd -c /etc/ocserv/ocpasswd -d 3ccol8
ocpasswd -c /etc/ocserv/ocpasswd -d jv7ntc
ocpasswd -c /etc/ocserv/ocpasswd -d 21fsl7
ocpasswd -c /etc/ocserv/ocpasswd -d LY2k4TgD
ocpasswd -c /etc/ocserv/ocpasswd -d 4vJux7Sr
ocpasswd -c /etc/ocserv/ocpasswd -d u8krknnZ
ocpasswd -c /etc/ocserv/ocpasswd -d zuax7Myw
ocpasswd -c /etc/ocserv/ocpasswd -d SzZmdN76
ocpasswd -c /etc/ocserv/ocpasswd -d KKX9Lg3x
ocpasswd -c /etc/ocserv/ocpasswd -d mjGwZpJ9
ocpasswd -c /etc/ocserv/ocpasswd -d B6mJxjxB
ocpasswd -c /etc/ocserv/ocpasswd -d F553Qg6E
ocpasswd -c /etc/ocserv/ocpasswd -d JS2mvGpv
ocpasswd -c /etc/ocserv/ocpasswd -d X5Q23LrJ
ocpasswd -c /etc/ocserv/ocpasswd -d 9dWjAJWj
ocpasswd -c /etc/ocserv/ocpasswd -d 5VHEAyjX
ocpasswd -c /etc/ocserv/ocpasswd -d yJPsdv2r
ocpasswd -c /etc/ocserv/ocpasswd -d Hk5tXT9X
ocpasswd -c /etc/ocserv/ocpasswd -d EwW6w2Hp
ocpasswd -c /etc/ocserv/ocpasswd -d H2vgv4Yk
ocpasswd -c /etc/ocserv/ocpasswd -d msqCard9
ocpasswd -c /etc/ocserv/ocpasswd -d YjXhy9Pr
ocpasswd -c /etc/ocserv/ocpasswd -d 3DDhsfth
ocpasswd -c /etc/ocserv/ocpasswd -d Gw8fdefQ
ocpasswd -c /etc/ocserv/ocpasswd -d LxY27PrK
ocpasswd -c /etc/ocserv/ocpasswd -d wqGvF9Hh
ocpasswd -c /etc/ocserv/ocpasswd -d jMzd6UDp
ocpasswd -c /etc/ocserv/ocpasswd -d NwmHHzw7
ocpasswd -c /etc/ocserv/ocpasswd -d UqcvR7pw
ocpasswd -c /etc/ocserv/ocpasswd -d aWp7xx22
ocpasswd -c /etc/ocserv/ocpasswd -d reM5HfMj
ocpasswd -c /etc/ocserv/ocpasswd -d vL688gB7
ocpasswd -c /etc/ocserv/ocpasswd -d h4PtaNMb
ocpasswd -c /etc/ocserv/ocpasswd -d FRPg9REq
ocpasswd -c /etc/ocserv/ocpasswd -d 6cpgsgrW
ocpasswd -c /etc/ocserv/ocpasswd -d W4kF79Ad
ocpasswd -c /etc/ocserv/ocpasswd -d 3JL4KgVQ
ocpasswd -c /etc/ocserv/ocpasswd -d 4BvyXwUn
ocpasswd -c /etc/ocserv/ocpasswd -d QG5xaNTs
ocpasswd -c /etc/ocserv/ocpasswd -d qEPHtt9Z
ocpasswd -c /etc/ocserv/ocpasswd -d HUDsm3mc
ocpasswd -c /etc/ocserv/ocpasswd -d 6awfDFLK
ocpasswd -c /etc/ocserv/ocpasswd -d kr3sd8NY
ocpasswd -c /etc/ocserv/ocpasswd -d r5MDbnQW
ocpasswd -c /etc/ocserv/ocpasswd -d fhQ7Shg3
ocpasswd -c /etc/ocserv/ocpasswd -d phRjs2ms
ocpasswd -c /etc/ocserv/ocpasswd -d 6dMafjMY
ocpasswd -c /etc/ocserv/ocpasswd -d JM4bMd8C
ocpasswd -c /etc/ocserv/ocpasswd -d C5gx6UnX
ocpasswd -c /etc/ocserv/ocpasswd -d 6QmN4wpt
ocpasswd -c /etc/ocserv/ocpasswd -d W52MHh4j
ocpasswd -c /etc/ocserv/ocpasswd -d WSmsJZQ6
ocpasswd -c /etc/ocserv/ocpasswd -d Pg7gEumD
ocpasswd -c /etc/ocserv/ocpasswd -d AdLRx8Su
ocpasswd -c /etc/ocserv/ocpasswd -d k9EjhCHw
ocpasswd -c /etc/ocserv/ocpasswd -d d7SDBPqd
ocpasswd -c /etc/ocserv/ocpasswd -d 4wTCZxJH
ocpasswd -c /etc/ocserv/ocpasswd -d vCn386gX
ocpasswd -c /etc/ocserv/ocpasswd -d g4cqfNnX
ocpasswd -c /etc/ocserv/ocpasswd -d kT8sNmSn
ocpasswd -c /etc/ocserv/ocpasswd -d WKYc5y9s
ocpasswd -c /etc/ocserv/ocpasswd -d ua9VjHpS
ocpasswd -c /etc/ocserv/ocpasswd -d C2kGRPKY
ocpasswd -c /etc/ocserv/ocpasswd -d VNnj7rTt
