#!/bin/sh -x
ocpasswd -c /etc/ocserv/ocpasswd -d 7nrf34
ocpasswd -c /etc/ocserv/ocpasswd -d 2cofo7
ocpasswd -c /etc/ocserv/ocpasswd -d b3n729
ocpasswd -c /etc/ocserv/ocpasswd -d s5rp6g
ocpasswd -c /etc/ocserv/ocpasswd -d 9rnea6
ocpasswd -c /etc/ocserv/ocpasswd -d 2tain7
ocpasswd -c /etc/ocserv/ocpasswd -d 6htag3
ocpasswd -c /etc/ocserv/ocpasswd -d vak3n6
ocpasswd -c /etc/ocserv/ocpasswd -d 5ssm02
ocpasswd -c /etc/ocserv/ocpasswd -d 4nyea9
ocpasswd -c /etc/ocserv/ocpasswd -d gb7utx
ocpasswd -c /etc/ocserv/ocpasswd -d 7sgme8
ocpasswd -c /etc/ocserv/ocpasswd -d 8369g5
ocpasswd -c /etc/ocserv/ocpasswd -d 2hooa7
ocpasswd -c /etc/ocserv/ocpasswd -d 3ngnt8
ocpasswd -c /etc/ocserv/ocpasswd -d dv2cpr
ocpasswd -c /etc/ocserv/ocpasswd -d 5maee2
ocpasswd -c /etc/ocserv/ocpasswd -d 2rgfh7
ocpasswd -c /etc/ocserv/ocpasswd -d 9taoe6
ocpasswd -c /etc/ocserv/ocpasswd -d ue4wyg
ocpasswd -c /etc/ocserv/ocpasswd -d 4nyea9
ocpasswd -c /etc/ocserv/ocpasswd -d 3thSpxB7
ocpasswd -c /etc/ocserv/ocpasswd -d yScA8fQu
ocpasswd -c /etc/ocserv/ocpasswd -d Lhq5FrgT
ocpasswd -c /etc/ocserv/ocpasswd -d J6jUZHG2
ocpasswd -c /etc/ocserv/ocpasswd -d UgBcvPE5
ocpasswd -c /etc/ocserv/ocpasswd -d EVgj7e4U
ocpasswd -c /etc/ocserv/ocpasswd -d 5RyvmMtU
ocpasswd -c /etc/ocserv/ocpasswd -d 9sgkLwe7
ocpasswd -c /etc/ocserv/ocpasswd -d J4z9dSFN
ocpasswd -c /etc/ocserv/ocpasswd -d 2J8zuKpm
ocpasswd -c /etc/ocserv/ocpasswd -d H9DEZzsA
ocpasswd -c /etc/ocserv/ocpasswd -d ePUT6Dkd
ocpasswd -c /etc/ocserv/ocpasswd -d wDMh9fg5
ocpasswd -c /etc/ocserv/ocpasswd -d hwnkLWd5
ocpasswd -c /etc/ocserv/ocpasswd -d gsPpZ3En
ocpasswd -c /etc/ocserv/ocpasswd -d wVduDBK8
ocpasswd -c /etc/ocserv/ocpasswd -d UzahsF46
ocpasswd -c /etc/ocserv/ocpasswd -d VCa5KDGL
ocpasswd -c /etc/ocserv/ocpasswd -d uPe3rZJg
ocpasswd -c /etc/ocserv/ocpasswd -d kR2rsQvG
ocpasswd -c /etc/ocserv/ocpasswd -d 7pGK538e
ocpasswd -c /etc/ocserv/ocpasswd -d c6pEjkzB
ocpasswd -c /etc/ocserv/ocpasswd -d sefjCbN3
ocpasswd -c /etc/ocserv/ocpasswd -d 3vXYTFh2
ocpasswd -c /etc/ocserv/ocpasswd -d g2kphHKF
ocpasswd -c /etc/ocserv/ocpasswd -d E4Mp2uhq
ocpasswd -c /etc/ocserv/ocpasswd -d xNkBzpG4
ocpasswd -c /etc/ocserv/ocpasswd -d QHhk9dyt
ocpasswd -c /etc/ocserv/ocpasswd -d 5Gn8HkVw
ocpasswd -c /etc/ocserv/ocpasswd -d PjUuL4Xh
ocpasswd -c /etc/ocserv/ocpasswd -d 59LMG2dU
ocpasswd -c /etc/ocserv/ocpasswd -d 5D7eQPwn
ocpasswd -c /etc/ocserv/ocpasswd -d YL9qPd37
ocpasswd -c /etc/ocserv/ocpasswd -d hM7H8rTw
ocpasswd -c /etc/ocserv/ocpasswd -d 2H9FpfEz
ocpasswd -c /etc/ocserv/ocpasswd -d N9sreUEQ
ocpasswd -c /etc/ocserv/ocpasswd -d 7s8q3xnE
ocpasswd -c /etc/ocserv/ocpasswd -d 4wNf2Qnz
ocpasswd -c /etc/ocserv/ocpasswd -d GtrmBYX8
ocpasswd -c /etc/ocserv/ocpasswd -d dZVcL7SY
ocpasswd -c /etc/ocserv/ocpasswd -d 3CsJtu9y
ocpasswd -c /etc/ocserv/ocpasswd -d vK4J7AVD
ocpasswd -c /etc/ocserv/ocpasswd -d Vqd9fYBN
ocpasswd -c /etc/ocserv/ocpasswd -d 8fsXVeS7
ocpasswd -c /etc/ocserv/ocpasswd -d c8StgPwf
ocpasswd -c /etc/ocserv/ocpasswd -d rH6KwsBf
ocpasswd -c /etc/ocserv/ocpasswd -d 3BcLfER4
ocpasswd -c /etc/ocserv/ocpasswd -d gRw2hEQC
ocpasswd -c /etc/ocserv/ocpasswd -d 4yf8Ye76
ocpasswd -c /etc/ocserv/ocpasswd -d 6kug4rTB
ocpasswd -c /etc/ocserv/ocpasswd -d vPyWrTN9
ocpasswd -c /etc/ocserv/ocpasswd -d NSXeUC6z
ocpasswd -c /etc/ocserv/ocpasswd -d 2hURxEf9
ocpasswd -c /etc/ocserv/ocpasswd -d AkDbZH8W
ocpasswd -c /etc/ocserv/ocpasswd -d 5AQDynbE
ocpasswd -c /etc/ocserv/ocpasswd -d HSxCc5uj
ocpasswd -c /etc/ocserv/ocpasswd -d K7buqvRr
ocpasswd -c /etc/ocserv/ocpasswd -d perXgJh2
ocpasswd -c /etc/ocserv/ocpasswd -d PM3a9wqL
ocpasswd -c /etc/ocserv/ocpasswd -d DGuZnS9v
ocpasswd -c /etc/ocserv/ocpasswd -d 6mXykzZP
ocpasswd -c /etc/ocserv/ocpasswd -d vT7x2gKS
ocpasswd -c /etc/ocserv/ocpasswd -d TVUrGZ5m
ocpasswd -c /etc/ocserv/ocpasswd -d JjZqcW2r
ocpasswd -c /etc/ocserv/ocpasswd -d EX2up9bD
ocpasswd -c /etc/ocserv/ocpasswd -d X6qBbFCH
ocpasswd -c /etc/ocserv/ocpasswd -d ZaKV7A84
ocpasswd -c /etc/ocserv/ocpasswd -d GteWpT3Y
ocpasswd -c /etc/ocserv/ocpasswd -d 92FzvcxG
ocpasswd -c /etc/ocserv/ocpasswd -d zutsmC7y
ocpasswd -c /etc/ocserv/ocpasswd -d axcr4uX7
ocpasswd -c /etc/ocserv/ocpasswd -d QHq6pgV4
ocpasswd -c /etc/ocserv/ocpasswd -d YUfGLS6E
ocpasswd -c /etc/ocserv/ocpasswd -d Lrwg8WfG
ocpasswd -c /etc/ocserv/ocpasswd -d D49b8trp
ocpasswd -c /etc/ocserv/ocpasswd -d LdX3m4hG
ocpasswd -c /etc/ocserv/ocpasswd -d g7TkZA4a
ocpasswd -c /etc/ocserv/ocpasswd -d SA2LwQJV
ocpasswd -c /etc/ocserv/ocpasswd -d 2v7XgQr6
ocpasswd -c /etc/ocserv/ocpasswd -d WRADs3Gw
ocpasswd -c /etc/ocserv/ocpasswd -d 2sAMrZqH
ocpasswd -c /etc/ocserv/ocpasswd -d XE7Wp6Vr
ocpasswd -c /etc/ocserv/ocpasswd -d 8Ts2jCe4
ocpasswd -c /etc/ocserv/ocpasswd -d h6rE3Yds
ocpasswd -c /etc/ocserv/ocpasswd -d JnP3ZYLp
ocpasswd -c /etc/ocserv/ocpasswd -d XE7Wp6Vr
ocpasswd -c /etc/ocserv/ocpasswd -d 2sAMrZqH
ocpasswd -c /etc/ocserv/ocpasswd -d 5ABcw4xj
ocpasswd -c /etc/ocserv/ocpasswd -d 5dug4ZNB
ocpasswd -c /etc/ocserv/ocpasswd -d 2QfwCLen
ocpasswd -c /etc/ocserv/ocpasswd -d 5RBLDYCt
ocpasswd -c /etc/ocserv/ocpasswd -d qS5PwGsE
ocpasswd -c /etc/ocserv/ocpasswd -d XDRx4qpe
ocpasswd -c /etc/ocserv/ocpasswd -d tB6sPqVN
